# Generated by Django 4.2.4 on 2024-02-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_special_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='Event.jpg', upload_to='Event')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.DeleteModel(
            name='Best_Products',
        ),
    ]
